# Ruff config
line-length = 88
indent-width = 4

# Assume Python 3.13
target-version = "py313"

[lint]
# Enable Pyflakes (`F`) and a subset of the pycodestyle (`E`) codes by default.
# Unlike Flake8, Ruff doesn't enable pycodestyle warnings (`W`) or
# McCabe complexity (`C901`) by default.
select = [
    "F",       # Pyflakes
    "ANN",     # Flake8-annotations
    "FBT",     # Avoid cryptic boolean args
    "B",       # Flake8-bugbear
    "A",       # Avoid shadowing Python builtins
    "C4",      # Comprehensions!
    "EXE",     # Scripts shebang related
    "FA",      # __future__ anotations
    "PYI",     # Stubs related
    "PT",      # Pytest related
    "RET",     # Return related
    "SIM",     # Simplify code
    "TID252",  # Avoid relative imports
    "ARG",     # Unused arguments
    "PTH",     # Prefer Pathlib over os
    "I",       # isort
    "C90",     # McCabe func complexity
    "PD",      # Pandas related
    "N",       # Pep8 naming
    "PERF",    # Performance related
    "E",       # Pycodestyle Errors
    "W",       # Pycodestyle warnings
    "D",       # Pydocstyle
    "PL",      # Pylint
    "UP",      # Use newer features
    "FURB",    # Newer features
    "RUF",     # Ruff based
    "TRY"      # Try-Except related
]
ignore = [
    "ANN401",  # Any-type is sometimes useful, specially for wrappers
    "D203",    # Blank line after class def
    "D212"     # Start docs next to quotes
]

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

[lint.pydocstyle]
convention = "numpy"

[format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"
