name: Python package CI/CD

on:
  push:
    branches:
      - "main"
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'  # Semantic versioning
  pull_request:
    branches:
      - "main"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Sync Project
        run: uv sync --locked --all-extras --dev

      - name: Run Tests
        run: uv run pytest

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: pytest-results
          path: |
            test_report.xml
            coverage.xml
      - name: Test report
        uses: dorny/test-reporter@v2
        if: ${{ !cancelled() }}  
        with:
          name: Pytest Tests      
          path: test_report.xml
          reporter: java-junit

  build:
    runs-on: ubuntu-latest
    needs: test
    if: startsWith(github.ref, 'refs/tags/')
    env:
      dist_artifacts_name: dist
      dist_artifacts_dir: dist
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Build Project
        run: uv build

      - name: Upload Distribution Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.dist_artifacts_name }}
          path: ${{ format('{0}/**', env.dist_artifacts_dir) }}
          if-no-files-found: error
          retention-days: 2

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Dist Artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Build Changelog
        id: release_changelog
        uses: mikepenz/release-changelog-builder-action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          body: ${{ steps.release_changelog.outputs.changelog }} 
          files: |
            dist/**
    